export const DRIVER_INTAKE_FIELDS = [
  "fullName",
  "phone",
  "companyName",
  "licenseNumber",
  "licenseExpiry",
  "experienceYears",
  "bankName",
  "bankAccountNumber",
  "bankIfsc",
  "pfAccountNumber",
  "uanNumber",
  "esicNumber",
  "bloodGroup",
  "fatherName",
  "fatherContact",
  "motherName",
  "motherContact",
  "spouseName",
  "spouseContact",
  "child1Name",
  "child2Name",
  "panOrVoterId",
  "aadhaarNo",
  "vehicleBusId",
  "vehicleRegistrationNo",
  "presentReadingKm",
  "badgeNo",
  "badgeValidity",
  "education",
  "dateOfBirth",
  "maritalStatus",
  "religion",
  "presentVillage",
  "presentLandmark",
  "presentPostOffice",
  "presentMandal",
  "presentPoliceStation",
  "presentDistrict",
  "presentState",
  "presentPinCode",
  "permanentVillage",
  "permanentLandmark",
  "permanentPostOffice",
  "permanentMandal",
  "permanentPoliceStation",
  "permanentDistrict",
  "permanentState",
  "permanentPinCode",
  "reference1Name",
  "reference1Relationship",
  "reference1Contact",
  "reference2Name",
  "reference2Relationship",
  "reference2Contact",
  "presentSalary",
  "salaryExpectation",
  "salaryOffered",
  "joiningDate",
  "candidateSignatureText",
  "candidateSignatureDate",
  "appointeeSignatureText",
  "approvalAuthoritySignatureText",
] as const;

export type DriverIntakeFieldKey = (typeof DRIVER_INTAKE_FIELDS)[number];

export const DRIVER_REQUIRED_FIELDS: DriverIntakeFieldKey[] = [
  "fullName",
  "phone",
  "licenseNumber",
  "licenseExpiry",
  "joiningDate",
];

export const DRIVER_DATE_FIELDS = new Set<DriverIntakeFieldKey>([
  "licenseExpiry",
  "badgeValidity",
  "dateOfBirth",
  "joiningDate",
  "candidateSignatureDate",
]);

export const DRIVER_NUMERIC_FIELDS = new Set<DriverIntakeFieldKey>([
  "experienceYears",
  "presentReadingKm",
  "presentSalary",
  "salaryExpectation",
  "salaryOffered",
]);

export const DRIVER_DIGIT_NORMALIZE_FIELDS = new Set<DriverIntakeFieldKey>([
  "phone",
  "fatherContact",
  "motherContact",
  "spouseContact",
  "reference1Contact",
  "reference2Contact",
  "aadhaarNo",
  "bankAccountNumber",
  "presentPinCode",
  "permanentPinCode",
]);

export const DRIVER_SECTION_FIELDS: Record<string, DriverIntakeFieldKey[]> = {
  Basic: ["fullName", "phone", "bloodGroup"],
  "Family Details": [
    "fatherName",
    "fatherContact",
    "motherName",
    "motherContact",
    "spouseName",
    "spouseContact",
    "child1Name",
    "child2Name",
  ],
  "Identity & Banking": [
    "panOrVoterId",
    "aadhaarNo",
    "bankAccountNumber",
    "bankName",
    "bankIfsc",
    "pfAccountNumber",
    "uanNumber",
    "esicNumber",
  ],
  "Vehicle & License": [
    "vehicleBusId",
    "vehicleRegistrationNo",
    "presentReadingKm",
    "licenseNumber",
    "licenseExpiry",
    "badgeNo",
    "badgeValidity",
  ],
  "Education & Personal Info": [
    "education",
    "experienceYears",
    "dateOfBirth",
    "maritalStatus",
    "religion",
    "companyName",
  ],
  "Present Address": [
    "presentVillage",
    "presentLandmark",
    "presentPostOffice",
    "presentMandal",
    "presentPoliceStation",
    "presentDistrict",
    "presentState",
    "presentPinCode",
  ],
  "Permanent Address": [
    "permanentVillage",
    "permanentLandmark",
    "permanentPostOffice",
    "permanentMandal",
    "permanentPoliceStation",
    "permanentDistrict",
    "permanentState",
    "permanentPinCode",
  ],
  "Reference Details": [
    "reference1Name",
    "reference1Relationship",
    "reference1Contact",
    "reference2Name",
    "reference2Relationship",
    "reference2Contact",
  ],
  "Salary Details": ["presentSalary", "salaryExpectation", "salaryOffered"],
  "Final Section": [
    "joiningDate",
    "candidateSignatureText",
    "candidateSignatureDate",
    "appointeeSignatureText",
    "approvalAuthoritySignatureText",
  ],
};

