export type ExportModuleKey =
  | "overall"
  | "buses"
  | "drivers"
  | "employees"
  | "routes"
  | "trips"
  | "tracking"
  | "fuel-trucks"
  | "finance"
  | "logs"
  | "users";

export type ExportField = { key: string; label: string };

export const MODULE_EXPORT_FIELDS: Record<ExportModuleKey, ExportField[]> = {
  overall: [
    { key: "module", label: "Module" },
    { key: "total_records", label: "Total Records" },
    { key: "active_records", label: "Active Records" },
    { key: "last_updated", label: "Last Updated" },
  ],
  buses: [
    { key: "id", label: "Bus ID" },
    { key: "bus_number", label: "Bus Number" },
    { key: "registration_number", label: "Registration" },
    { key: "make", label: "Make" },
    { key: "model", label: "Model" },
    { key: "seater", label: "Seater" },
    { key: "status", label: "Status" },
    { key: "odometer_km", label: "Odometer (km)" },
    { key: "previous_day_mileage_kmpl", label: "Previous Day Mileage (KM/L)" },
    { key: "total_fuel_liters", label: "Total Fuel (L)" },
    { key: "total_fuel_amount", label: "Total Fuel Amount" },
    { key: "total_km_run", label: "Total KM Run" },
    { key: "overall_mileage_kmpl", label: "Overall Mileage (KM/L)" },
    { key: "last_fuel_date", label: "Last Fuel Date" },
    { key: "last_odometer_start", label: "Last Odometer Start" },
    { key: "last_odometer_end", label: "Last Odometer End" },
    { key: "last_fuel_liters", label: "Last Fuel (L)" },
    { key: "last_fuel_amount", label: "Last Fuel Amount" },
    { key: "last_company_name", label: "Last Company" },
  ],
  drivers: [
    { key: "id", label: "Driver ID" },
    { key: "full_name", label: "Name" },
    { key: "phone", label: "Phone" },
    { key: "company_name", label: "Company" },
    { key: "blood_group", label: "Blood Group" },
    { key: "father_name", label: "Father Name" },
    { key: "father_contact", label: "Father Contact" },
    { key: "mother_name", label: "Mother Name" },
    { key: "mother_contact", label: "Mother Contact" },
    { key: "spouse_name", label: "Spouse Name" },
    { key: "spouse_contact", label: "Spouse Contact" },
    { key: "child_1_name", label: "Child 1" },
    { key: "child_2_name", label: "Child 2" },
    { key: "pan_or_voter_id", label: "PAN / Voter ID" },
    { key: "aadhaar_no", label: "Aadhaar" },
    { key: "bank_name", label: "Bank Name" },
    { key: "bank_account_number", label: "Bank Account Number" },
    { key: "bank_ifsc", label: "IFSC" },
    { key: "pf_account_number", label: "PF / EPF Account No" },
    { key: "uan_number", label: "UAN No" },
    { key: "esic_number", label: "ESIC No" },
    { key: "vehicle_registration_no", label: "Vehicle Registration" },
    { key: "present_reading_km", label: "Present Reading (KM)" },
    { key: "license_number", label: "License" },
    { key: "license_expiry", label: "License Validity" },
    { key: "badge_no", label: "Badge No" },
    { key: "badge_validity", label: "Badge Validity" },
    { key: "education", label: "Education" },
    { key: "experience_years", label: "Experience (Years)" },
    { key: "date_of_birth", label: "Date of Birth" },
    { key: "marital_status", label: "Marital Status" },
    { key: "religion", label: "Religion" },
    { key: "present_village", label: "Present Village" },
    { key: "present_landmark", label: "Present Landmark" },
    { key: "present_post_office", label: "Present Post Office" },
    { key: "present_mandal", label: "Present Mandal" },
    { key: "present_police_station", label: "Present Police Station" },
    { key: "present_district", label: "Present District" },
    { key: "present_state", label: "Present State" },
    { key: "present_pin_code", label: "Present Pin Code" },
    { key: "permanent_village", label: "Permanent Village" },
    { key: "permanent_landmark", label: "Permanent Landmark" },
    { key: "permanent_post_office", label: "Permanent Post Office" },
    { key: "permanent_mandal", label: "Permanent Mandal" },
    { key: "permanent_police_station", label: "Permanent Police Station" },
    { key: "permanent_district", label: "Permanent District" },
    { key: "permanent_state", label: "Permanent State" },
    { key: "permanent_pin_code", label: "Permanent Pin Code" },
    { key: "reference1_name", label: "Reference 1 Name" },
    { key: "reference1_relationship", label: "Reference 1 Relationship" },
    { key: "reference1_contact", label: "Reference 1 Contact" },
    { key: "reference2_name", label: "Reference 2 Name" },
    { key: "reference2_relationship", label: "Reference 2 Relationship" },
    { key: "reference2_contact", label: "Reference 2 Contact" },
    { key: "present_salary", label: "Present Salary" },
    { key: "salary_expectation", label: "Salary Expectation" },
    { key: "salary_offered", label: "Salary Offered" },
    { key: "joining_date", label: "Joining Date" },
    { key: "candidate_signature_text", label: "Candidate Signature / Date" },
    { key: "candidate_signature_date", label: "Candidate Signature Date" },
    { key: "appointee_signature_text", label: "Signature of Appointee" },
    { key: "approval_authority_signature_text", label: "Signature of Approval Authority" },
    { key: "is_active", label: "Active" },
    { key: "updated_at", label: "Updated At" },
  ],
  employees: [
    { key: "employee_code", label: "Employee Code" },
    { key: "full_name", label: "Name" },
    { key: "phone", label: "Phone" },
    { key: "department", label: "Department" },
    { key: "company_name", label: "Company" },
    { key: "is_active", label: "Active" },
  ],
  routes: [
    { key: "assignment_date", label: "Date" },
    { key: "route_name", label: "Route" },
    { key: "shift", label: "Shift" },
    { key: "company_name", label: "Company" },
    { key: "bus_registration_number", label: "Registration" },
    { key: "driver_name", label: "Driver" },
  ],
  trips: [
    { key: "trip_date", label: "Date" },
    { key: "status", label: "Status" },
    { key: "bus_number", label: "Bus" },
    { key: "driver_name", label: "Driver" },
    { key: "route_name", label: "Route" },
    { key: "shift_label", label: "Shift" },
    { key: "km_run", label: "KM Run" },
    { key: "mileage_kmpl", label: "Mileage" },
  ],
  tracking: [
    { key: "logged_at", label: "Logged At" },
    { key: "bus_number", label: "Bus" },
    { key: "latitude", label: "Latitude" },
    { key: "longitude", label: "Longitude" },
    { key: "speed_kmph", label: "Speed" },
  ],
  "fuel-trucks": [
    { key: "issue_date", label: "Issue Date" },
    { key: "truck_code", label: "Truck" },
    { key: "registration_number", label: "Registration" },
    { key: "liters_issued", label: "Liters Issued" },
    { key: "amount", label: "Amount" },
    { key: "company_name", label: "Company" },
  ],
  finance: [
    { key: "registration_no", label: "Registration" },
    { key: "vehicle_type_or_bus_name", label: "Vehicle" },
    { key: "financier_bank_name", label: "Financier" },
    { key: "loan_amount_taken", label: "Loan Amount" },
    { key: "emi_amount", label: "EMI" },
    { key: "outstanding_principal", label: "Outstanding Principal" },
    { key: "status", label: "Status" },
  ],
  logs: [
    { key: "created_at", label: "Time" },
    { key: "user_email", label: "User" },
    { key: "action", label: "Action" },
    { key: "entity_type", label: "Entity Type" },
    { key: "entity_id", label: "Entity ID" },
  ],
  users: [
    { key: "full_name", label: "Name" },
    { key: "email", label: "Email" },
    { key: "role", label: "Role" },
    { key: "is_active", label: "Active" },
    { key: "updated_at", label: "Updated At" },
  ],
};
